mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  servlet:
    context-path: /ml
  port: 8054

spring:
  application:
    name: machine-learning
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.66.223.140:5432/fox?useUnicode=true&characterEncoding=utf-8&useSSL=false&currentSchema=fox
    username: fox
    password: 0GwFLRQJCBYhxB0E
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    publisher-confirms: true
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual

spark:
  spark-home: .
  app-name: sparkTest
  master: local[4]